### ISSUE TITLE
Report a bug about last commit on 2017.3.5

### ISSUE THREAD

**Issue by zhangguanqun** [CongWeilin/mtcnn-caffe#13]
When switching from tools.py to tools_matrix.py, running 'python test.py', I got a error msg:
Traceback (most recent call last):
  File "test.py", line 84, in <module>
    rectangles = detectFace(imgpath,threshold)
  File "test.py", line 54, in detectFace
    crop_img = caffe_img[rectangle[1]:rectangle[3], rectangle[0]:rectangle[2]]
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by CongWeilin** [comment]
Thanks. replace rectangle[1]:rectangle[3], rectangle[0]:rectangle[2] with int(rectangle[1]):int(rectangle[3]),int(rectangle[0]):int(rectangle[2]) will fix this problem.
