### ISSUE TITLE
imdb problem

### ISSUE THREAD

**Issue by jmu201521121021** [CongWeilin/mtcnn-caffe#24]
after python gen_48net_data.py, when python gen_net_imdb.py, erro:File "gen_net_imdb.py", line 38, in <module>
    h,w,ch = im.shape
AttributeError: 'NoneType' object has no attribute 'shape'
why ?

**Comment by CongWeilin** [comment]
it means no image was read by cv2.
check image path

**Comment by herleeyandi** [comment]
Since I am new in this stuff:
1) I got error like this
NameError: name 'pos2' is not defined
I just realize that I must define Pos2, but in the begining it use Pos
After that I got this error
`Traceback (most recent call last):`
`  File "gen_net_imdb.py", line 47, in <module>`
`    neg_keep = npr.choice(len(neg2), size=600000, replace=False)`
`  File "mtrand.pyx", line 1104, in mtrand.RandomState.choice (numpy/random/mtrand/mtrand.c:17062)`
`ValueError: a must be greater than 0`
So in here I have problem when the code has no documentation. It really hard for me to define which part should be have role in changing the parameter. I still not figuring out what is the problem of this error.

**Comment by jmu201521121021** [comment]
I also got the same erro，but change pos to pos2，problem solved

**Comment by herleeyandi** [comment]
I have solved this error but now I have the same error like you @jmu201521121021 . I guess it is because the path of the image. Do you change something (like image path)  in pos.txt, part.txt, neg.txt?

**Comment by jmu201521121021** [comment]
No，i did not solve it now，i also 
think it is becouse it is the path of image.

**Comment by herleeyandi** [comment]
I solve it @jmu201521121021 , first you must create 3 folder inside `48` folder, so it becomes `/48/positive` `/48/negative` `/48/part` then you must change the path in gen_net_imdb.py to point to folder. This can be simply doing by replace `../48net` by the location of `48` folder.
The process will be so long and make my pc not responding.
Then after I try to see it, I just know that `pickle.dump(roi_list, fid)` operation while I break it, the imdb data of  `cls.imdb` and `roi.imdb` has been formed.
Now the problem is I dont get `pts.imdb` I think I just need to change code, and I just don't know how we doing train.
@CongWeilin How do we train using train.prototxt?, are you load the imdb file in pythonlayer.py?

**Comment by liuyue88** [comment]
Herleeyandi, hello, is your problem solved? I encountered IOError when training 12net: [Errno 2] No such file or directory: '12 /pts.imdb ', how to get pts.imdb ah

**Comment by herleeyandi** [comment]
Hi @liuyue88 sorry I didin't continue to train this method. Actually we must need the dataset which has the groundtruth of pts. I haven't found the dataset which has 3 of them. First is class which face/non-face, second is ROI, and third is points of landmarks. Last time I just find class, and ROI dataset in the suggested database, so I am not training this method. I will try it later when have time again. If I found it, I will tell you.
My suggestion:
I have a way to do that but I have limited times, so I haven't done it yet. You can see this landmark dataset https://ibug.doc.ic.ac.uk/resources/facial-point-annotations/ .Then you can create the code for ROI Coordinat with the outer landmarks. After that generate the dataset using the `prepare_dataset` which provided in this repository.

**Comment by liuyue88** [comment]
Thank you
