### ISSUE TITLE
Hard Example "cls_score"

### ISSUE THREAD

**Issue by herleeyandi** [CongWeilin/mtcnn-caffe#30]
I have problem in prepare data for hard example.py . Currently I want to train to 68 landmarks using 48Net. But in here @CongWeilin  suggest me to `Similar to last step, Run gen_24net_hard_example.py to generate hard sample. Run gen_48net_data.py. Combine these output and generate imdb`
1) What is the mean by combine its output?
2) The problem in gen_hard_example 24 net. Here is the error:
`Traceback (most recent call last):`
  `File "gen_24net_hard_example.py", line 91, in <module>`
   ` rectangles = detectFace(img_path,threshold)`
 ` File "gen_24net_hard_example.py", line 44, in detectFace`
    `cls_prob = out[i]['cls_score'][0][1]`
`KeyError: 'cls_score'`
Actually the first I am change the path of caffe, then the location of prototxt and caffe model inside `demo` folder.
3) How can I assign the groundtruth of 68 landmarks?
Anyone can help me, please I need some hints and suggestions, since I am new in this stuff.
-Thank you-

**Comment by luckycookiecookie** [comment]
hi，i have the same problem with you, have you solved it? @herleeyandi

**Comment by Rainy000** [comment]
Do you have finished the training process of PNet and RNet ? I encountered one problem that the PNet and RNet training process can not converge, the accuracy rate always  stay at 48%~60%, anyone can give me some suggestions ?

**Comment by herleeyandi** [comment]
@luckycookiecookie Actually you can change "cls_score" to "prob1" . Also another parameter which given in the prototxt. Have you done your training?
@Rainy000 Wow cool, I haven't continue it yet. How can you produce the pts.imdb?, what kind of dataset did you use?
-Thank you-

**Comment by Rainy000** [comment]
@herleeyandi Sorry, I switch to MXNET, but the ideas is same. I use Widerface for face detection and Celeba for landmark. Celeba dataset only have 5 points in each face image, if you want to train 68 landmarks ,maybe you can reference this website:[ https://ibug.doc.ic.ac.uk/resources/300-W/](url)
